#!python3

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                             1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
MAX = 4000000
#MAX = 100

#1. function fibonacci(n)
fib_1 = 1
fib_2 = 2
sum = 2 

while True:
    fib_1 = fib_1 + fib_2 # fib(n) = fib(n-2) + fib(n-1)
    if (fib_1 > MAX):
        break
    elif (fib_1%2 == 0 ):
        sum += fib_1
    fib_2 = fib_2 + fib_1 # fib(n+1) = fib(n-1) + fib(n)
    if (fib_2 > MAX):
        break
    elif (fib_2%2 == 0 ):
        sum += fib_2

print(sum)
